# Configuration for The-Mind Repository Automation Scripts

api_endpoints:
  leetcode: "https://leetcode.com/graphql"
  codeforces: "https://codeforces.com/api/"
  steam: "https://api.steampowered.com"
  chesscom: "https://api.chess.com/pub"

paths:
  # Directories (relative to project root)
  
  temp: "Temp"
  scripts_dir: "scripts"

  # Files (relative to project root)
  

  # Profile output files (filenames only, will be placed in 'shared' dir)
  
  
  
  
  
  pcspecs_output: "PCSpecs.txt"
  
  # Google credentials (filenames only, will be placed in 'scripts_dir')
  token_file: "token.json"
  creds_file: "credentials.json"

auth:
  url_file: "auth_url.txt"
  code_file: "auth_code.txt"

cloud:
  gdrive_books_path: "Books/PDFs"
  google_scopes:
    - "https://www.googleapis.com/auth/drive"
    - "https://www.googleapis.com/auth/documents"
    - "https://www.googleapis.com/auth/youtube.readonly"


