name: The Automaton Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 18,6 * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

  generate-and-sync-codeforces:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Run Codeforces Workflow
      run: |
        chmod +x scripts/workflow.sh
        ./scripts/workflow.sh codeforces
      env:
        EMAIL_ID: ${{ secrets.EMAIL_ID }}
        CODEFORCES_ID: ${{ secrets.CODEFORCES_ID }}
        GOOGLE_DOC_CODEFORCES_ID: ${{ secrets.GOOGLE_DOC_CODEFORCES_ID }}

  generate-and-sync-leetcode:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Run LeetCode Workflow
      run: |
        chmod +x scripts/workflow.sh
        ./scripts/workflow.sh leetcode
      env:
        EMAIL_ID: ${{ secrets.EMAIL_ID }}
        LEETCODE_ID: ${{ secrets.LEETCODE_ID }}
        GOOGLE_DOC_LEETCODE_ID: ${{ secrets.GOOGLE_DOC_LEETCODE_ID }}

  generate-and-sync-steam:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Run Steam Workflow
      run: |
        chmod +x scripts/workflow.sh
        ./scripts/workflow.sh steam-stats
      env:
        EMAIL_ID: ${{ secrets.EMAIL_ID }}
        STEAM_ID: ${{ secrets.STEAM_ID }}
        STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
        GOOGLE_DOC_STEAM_ID: ${{ secrets.GOOGLE_DOC_STEAM_ID }}

  generate-and-sync-youtube:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Run YouTube Workflow
      run: |
        chmod +x scripts/workflow.sh
        ./scripts/workflow.sh youtube
      env:
        EMAIL_ID: ${{ secrets.EMAIL_ID }}
        YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
        GOOGLE_DOC_YOUTUBE_ID: ${{ secrets.GOOGLE_DOC_YOUTUBE_ID }}

  generate-and-sync-chesscom:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Run Chess.com Workflow
      run: |
        chmod +x scripts/workflow.sh
        ./scripts/workflow.sh chess-com
      env:
        EMAIL_ID: ${{ secrets.EMAIL_ID }}
        CHESSCOM_ID: ${{ secrets.CHESSCOM_ID }}
        GOOGLE_DOC_CHESSCOM_ID: ${{ secrets.GOOGLE_DOC_CHESSCOM_ID }}
