name: The Automaton Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 18,6 * * *'

jobs:
  authenticate-service-account:
    runs-on: ubuntu-latest
    steps:
    - name: Authenticate to Google (once)
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        create_credentials_file: true

    - name: Upload service account credentials artifact
      uses: actions/upload-artifact@v4
      with:
        name: gcp-credentials
        path: ${{ steps.auth.outputs.credentials_file_path }}

  generate-and-sync-codeforces:
    runs-on: ubuntu-latest
    needs: authenticate-service-account
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Download service account credentials
      uses: actions/download-artifact@v4
      with:
        name: gcp-credentials
        path: gcp-creds

    - name: Prepare service account file for scripts
      run: |
        mkdir -p Temp
        cp gcp-creds/*.json Temp/service_account_key.json

    - name: Run Codeforces Workflow
      run: |
        chmod +x scripts/workflow.sh
        ./scripts/workflow.sh codeforces
      env:
        EMAIL_ID: ${{ secrets.EMAIL_ID }}
        CODEFORCES_ID: ${{ secrets.CODEFORCES_ID }}
        GOOGLE_DOC_CODEFORCES_ID: ${{ secrets.GOOGLE_DOC_CODEFORCES_ID }}
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_AUTH_URI: ${{ secrets.GOOGLE_AUTH_URI }}
        GOOGLE_TOKEN_URI: ${{ secrets.GOOGLE_TOKEN_URI }}
        GOOGLE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.GOOGLE_AUTH_PROVIDER_X509_CERT_URL }}
        GOOGLE_REDIRECT_URIS: ${{ secrets.GOOGLE_REDIRECT_URIS }}

  generate-and-sync-leetcode:
    runs-on: ubuntu-latest
    needs: authenticate-service-account
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Download service account credentials
      uses: actions/download-artifact@v4
      with:
        name: gcp-credentials
        path: gcp-creds

    - name: Prepare service account file for scripts
      run: |
        mkdir -p Temp
        cp gcp-creds/*.json Temp/service_account_key.json

    - name: Run LeetCode Workflow
      run: |
        chmod +x scripts/workflow.sh
        ./scripts/workflow.sh leetcode
      env:
        EMAIL_ID: ${{ secrets.EMAIL_ID }}
        LEETCODE_ID: ${{ secrets.LEETCODE_ID }}
        GOOGLE_DOC_LEETCODE_ID: ${{ secrets.GOOGLE_DOC_LEETCODE_ID }}
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_AUTH_URI: ${{ secrets.GOOGLE_AUTH_URI }}
        GOOGLE_TOKEN_URI: ${{ secrets.GOOGLE_TOKEN_URI }}
        GOOGLE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.GOOGLE_AUTH_PROVIDER_X509_CERT_URL }}
        GOOGLE_REDIRECT_URIS: ${{ secrets.GOOGLE_REDIRECT_URIS }}

  generate-and-sync-steam:
    runs-on: ubuntu-latest
    needs: authenticate-service-account
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Download service account credentials
      uses: actions/download-artifact@v4
      with:
        name: gcp-credentials
        path: gcp-creds

    - name: Prepare service account file for scripts
      run: |
        mkdir -p Temp
        cp gcp-creds/*.json Temp/service_account_key.json

    - name: Run Steam Workflow
      run: |
        chmod +x scripts/workflow.sh
        ./scripts/workflow.sh steam-stats
      env:
        EMAIL_ID: ${{ secrets.EMAIL_ID }}
        STEAM_ID: ${{ secrets.STEAM_ID }}
        STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
        GOOGLE_DOC_STEAM_ID: ${{ secrets.GOOGLE_DOC_STEAM_ID }}
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_AUTH_URI: ${{ secrets.GOOGLE_AUTH_URI }}
        GOOGLE_TOKEN_URI: ${{ secrets.GOOGLE_TOKEN_URI }}
        GOOGLE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.GOOGLE_AUTH_PROVIDER_X509_CERT_URL }}
        GOOGLE_REDIRECT_URIS: ${{ secrets.GOOGLE_REDIRECT_URIS }}

  generate-and-sync-youtube:
    runs-on: ubuntu-latest
    needs: authenticate-service-account
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Download service account credentials
      uses: actions/download-artifact@v4
      with:
        name: gcp-credentials
        path: gcp-creds

    - name: Prepare service account file for scripts
      run: |
        mkdir -p Temp
        cp gcp-creds/*.json Temp/service_account_key.json

    - name: Run YouTube Workflow
      run: |
        chmod +x scripts/workflow.sh
        ./scripts/workflow.sh youtube
      env:
        EMAIL_ID: ${{ secrets.EMAIL_ID }}
        YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
        GOOGLE_DOC_YOUTUBE_ID: ${{ secrets.GOOGLE_DOC_YOUTUBE_ID }}
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_AUTH_URI: ${{ secrets.GOOGLE_AUTH_URI }}
        GOOGLE_TOKEN_URI: ${{ secrets.GOOGLE_TOKEN_URI }}
        GOOGLE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.GOOGLE_AUTH_PROVIDER_X509_CERT_URL }}
        GOOGLE_REDIRECT_URIS: ${{ secrets.GOOGLE_REDIRECT_URIS }}

  generate-and-sync-chesscom:
    runs-on: ubuntu-latest
    needs: authenticate-service-account
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Download service account credentials
      uses: actions/download-artifact@v4
      with:
        name: gcp-credentials
        path: gcp-creds

    - name: Prepare service account file for scripts
      run: |
        mkdir -p Temp
        cp gcp-creds/*.json Temp/service_account_key.json

    - name: Run Chess.com Workflow
      run: |
        chmod +x scripts/workflow.sh
        ./scripts/workflow.sh chess-com
      env:
        EMAIL_ID: ${{ secrets.EMAIL_ID }}
        CHESSCOM_ID: ${{ secrets.CHESSCOM_ID }}
        GOOGLE_DOC_CHESSCOM_ID: ${{ secrets.GOOGLE_DOC_CHESSCOM_ID }}
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_AUTH_URI: ${{ secrets.GOOGLE_AUTH_URI }}
        GOOGLE_TOKEN_URI: ${{ secrets.GOOGLE_TOKEN_URI }}
        GOOGLE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.GOOGLE_AUTH_PROVIDER_X509_CERT_URL }}
        GOOGLE_REDIRECT_URIS: ${{ secrets.GOOGLE_REDIRECT_URIS }}
